# Generated by Django 2.1.2 on 2018-11-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0003_modified password field'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
