# Generated by Django 2.1.2 on 2018-11-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0005_made field email non unique to myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='access_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
